/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientiIndexRouteImport } from './routes/clienti.index'
import { Route as ClientiNuovoRouteImport } from './routes/clienti.nuovo'
import { Route as ClientiClientIdRouteImport } from './routes/clienti.$clientId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiIndexRoute = ClientiIndexRouteImport.update({
  id: '/clienti/',
  path: '/clienti/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiNuovoRoute = ClientiNuovoRouteImport.update({
  id: '/clienti/nuovo',
  path: '/clienti/nuovo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiClientIdRoute = ClientiClientIdRouteImport.update({
  id: '/clienti/$clientId',
  path: '/clienti/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clienti/$clientId': typeof ClientiClientIdRoute
  '/clienti/nuovo': typeof ClientiNuovoRoute
  '/clienti/': typeof ClientiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clienti/$clientId': typeof ClientiClientIdRoute
  '/clienti/nuovo': typeof ClientiNuovoRoute
  '/clienti': typeof ClientiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clienti/$clientId': typeof ClientiClientIdRoute
  '/clienti/nuovo': typeof ClientiNuovoRoute
  '/clienti/': typeof ClientiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/clienti/$clientId'
    | '/clienti/nuovo'
    | '/clienti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/clienti/$clientId'
    | '/clienti/nuovo'
    | '/clienti'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/clienti/$clientId'
    | '/clienti/nuovo'
    | '/clienti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ClientiClientIdRoute: typeof ClientiClientIdRoute
  ClientiNuovoRoute: typeof ClientiNuovoRoute
  ClientiIndexRoute: typeof ClientiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti/': {
      id: '/clienti/'
      path: '/clienti'
      fullPath: '/clienti/'
      preLoaderRoute: typeof ClientiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti/nuovo': {
      id: '/clienti/nuovo'
      path: '/clienti/nuovo'
      fullPath: '/clienti/nuovo'
      preLoaderRoute: typeof ClientiNuovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti/$clientId': {
      id: '/clienti/$clientId'
      path: '/clienti/$clientId'
      fullPath: '/clienti/$clientId'
      preLoaderRoute: typeof ClientiClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ClientiClientIdRoute: ClientiClientIdRoute,
  ClientiNuovoRoute: ClientiNuovoRoute,
  ClientiIndexRoute: ClientiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
