/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as SpeseRouteImport } from './routes/spese'
import { Route as ScadenzeRouteImport } from './routes/scadenze'
import { Route as ReimpostaPasswordRouteImport } from './routes/reimposta-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecuperaPasswordRouteImport } from './routes/recupera-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NovitaRouteImport } from './routes/novita'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PraticheIndexRouteImport } from './routes/pratiche.index'
import { Route as FattureIndexRouteImport } from './routes/fatture.index'
import { Route as ClientiIndexRouteImport } from './routes/clienti.index'
import { Route as PraticheNuovaRouteImport } from './routes/pratiche.nuova'
import { Route as PraticheCaseIdRouteImport } from './routes/pratiche.$caseId'
import { Route as FattureNuovaRouteImport } from './routes/fatture.nuova'
import { Route as FattureInvoiceIdRouteImport } from './routes/fatture.$invoiceId'
import { Route as ClientiNuovoRouteImport } from './routes/clienti.nuovo'
import { Route as ClientiClientIdRouteImport } from './routes/clienti.$clientId'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeseRoute = SpeseRouteImport.update({
  id: '/spese',
  path: '/spese',
  getParentRoute: () => rootRouteImport,
} as any)
const ScadenzeRoute = ScadenzeRouteImport.update({
  id: '/scadenze',
  path: '/scadenze',
  getParentRoute: () => rootRouteImport,
} as any)
const ReimpostaPasswordRoute = ReimpostaPasswordRouteImport.update({
  id: '/reimposta-password',
  path: '/reimposta-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperaPasswordRoute = RecuperaPasswordRouteImport.update({
  id: '/recupera-password',
  path: '/recupera-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NovitaRoute = NovitaRouteImport.update({
  id: '/novita',
  path: '/novita',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticheIndexRoute = PraticheIndexRouteImport.update({
  id: '/pratiche/',
  path: '/pratiche/',
  getParentRoute: () => rootRouteImport,
} as any)
const FattureIndexRoute = FattureIndexRouteImport.update({
  id: '/fatture/',
  path: '/fatture/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiIndexRoute = ClientiIndexRouteImport.update({
  id: '/clienti/',
  path: '/clienti/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticheNuovaRoute = PraticheNuovaRouteImport.update({
  id: '/pratiche/nuova',
  path: '/pratiche/nuova',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticheCaseIdRoute = PraticheCaseIdRouteImport.update({
  id: '/pratiche/$caseId',
  path: '/pratiche/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const FattureNuovaRoute = FattureNuovaRouteImport.update({
  id: '/fatture/nuova',
  path: '/fatture/nuova',
  getParentRoute: () => rootRouteImport,
} as any)
const FattureInvoiceIdRoute = FattureInvoiceIdRouteImport.update({
  id: '/fatture/$invoiceId',
  path: '/fatture/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiNuovoRoute = ClientiNuovoRouteImport.update({
  id: '/clienti/nuovo',
  path: '/clienti/nuovo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientiClientIdRoute = ClientiClientIdRouteImport.update({
  id: '/clienti/$clientId',
  path: '/clienti/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/login': typeof LoginRoute
  '/novita': typeof NovitaRoute
  '/privacy': typeof PrivacyRoute
  '/recupera-password': typeof RecuperaPasswordRoute
  '/register': typeof RegisterRoute
  '/reimposta-password': typeof ReimpostaPasswordRoute
  '/scadenze': typeof ScadenzeRoute
  '/spese': typeof SpeseRoute
  '/termini': typeof TerminiRoute
  '/clienti/$clientId': typeof ClientiClientIdRoute
  '/clienti/nuovo': typeof ClientiNuovoRoute
  '/fatture/$invoiceId': typeof FattureInvoiceIdRoute
  '/fatture/nuova': typeof FattureNuovaRoute
  '/pratiche/$caseId': typeof PraticheCaseIdRoute
  '/pratiche/nuova': typeof PraticheNuovaRoute
  '/clienti/': typeof ClientiIndexRoute
  '/fatture/': typeof FattureIndexRoute
  '/pratiche/': typeof PraticheIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/login': typeof LoginRoute
  '/novita': typeof NovitaRoute
  '/privacy': typeof PrivacyRoute
  '/recupera-password': typeof RecuperaPasswordRoute
  '/register': typeof RegisterRoute
  '/reimposta-password': typeof ReimpostaPasswordRoute
  '/scadenze': typeof ScadenzeRoute
  '/spese': typeof SpeseRoute
  '/termini': typeof TerminiRoute
  '/clienti/$clientId': typeof ClientiClientIdRoute
  '/clienti/nuovo': typeof ClientiNuovoRoute
  '/fatture/$invoiceId': typeof FattureInvoiceIdRoute
  '/fatture/nuova': typeof FattureNuovaRoute
  '/pratiche/$caseId': typeof PraticheCaseIdRoute
  '/pratiche/nuova': typeof PraticheNuovaRoute
  '/clienti': typeof ClientiIndexRoute
  '/fatture': typeof FattureIndexRoute
  '/pratiche': typeof PraticheIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/login': typeof LoginRoute
  '/novita': typeof NovitaRoute
  '/privacy': typeof PrivacyRoute
  '/recupera-password': typeof RecuperaPasswordRoute
  '/register': typeof RegisterRoute
  '/reimposta-password': typeof ReimpostaPasswordRoute
  '/scadenze': typeof ScadenzeRoute
  '/spese': typeof SpeseRoute
  '/termini': typeof TerminiRoute
  '/clienti/$clientId': typeof ClientiClientIdRoute
  '/clienti/nuovo': typeof ClientiNuovoRoute
  '/fatture/$invoiceId': typeof FattureInvoiceIdRoute
  '/fatture/nuova': typeof FattureNuovaRoute
  '/pratiche/$caseId': typeof PraticheCaseIdRoute
  '/pratiche/nuova': typeof PraticheNuovaRoute
  '/clienti/': typeof ClientiIndexRoute
  '/fatture/': typeof FattureIndexRoute
  '/pratiche/': typeof PraticheIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/impostazioni'
    | '/login'
    | '/novita'
    | '/privacy'
    | '/recupera-password'
    | '/register'
    | '/reimposta-password'
    | '/scadenze'
    | '/spese'
    | '/termini'
    | '/clienti/$clientId'
    | '/clienti/nuovo'
    | '/fatture/$invoiceId'
    | '/fatture/nuova'
    | '/pratiche/$caseId'
    | '/pratiche/nuova'
    | '/clienti/'
    | '/fatture/'
    | '/pratiche/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/impostazioni'
    | '/login'
    | '/novita'
    | '/privacy'
    | '/recupera-password'
    | '/register'
    | '/reimposta-password'
    | '/scadenze'
    | '/spese'
    | '/termini'
    | '/clienti/$clientId'
    | '/clienti/nuovo'
    | '/fatture/$invoiceId'
    | '/fatture/nuova'
    | '/pratiche/$caseId'
    | '/pratiche/nuova'
    | '/clienti'
    | '/fatture'
    | '/pratiche'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/impostazioni'
    | '/login'
    | '/novita'
    | '/privacy'
    | '/recupera-password'
    | '/register'
    | '/reimposta-password'
    | '/scadenze'
    | '/spese'
    | '/termini'
    | '/clienti/$clientId'
    | '/clienti/nuovo'
    | '/fatture/$invoiceId'
    | '/fatture/nuova'
    | '/pratiche/$caseId'
    | '/pratiche/nuova'
    | '/clienti/'
    | '/fatture/'
    | '/pratiche/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImpostazioniRoute: typeof ImpostazioniRoute
  LoginRoute: typeof LoginRoute
  NovitaRoute: typeof NovitaRoute
  PrivacyRoute: typeof PrivacyRoute
  RecuperaPasswordRoute: typeof RecuperaPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ReimpostaPasswordRoute: typeof ReimpostaPasswordRoute
  ScadenzeRoute: typeof ScadenzeRoute
  SpeseRoute: typeof SpeseRoute
  TerminiRoute: typeof TerminiRoute
  ClientiClientIdRoute: typeof ClientiClientIdRoute
  ClientiNuovoRoute: typeof ClientiNuovoRoute
  FattureInvoiceIdRoute: typeof FattureInvoiceIdRoute
  FattureNuovaRoute: typeof FattureNuovaRoute
  PraticheCaseIdRoute: typeof PraticheCaseIdRoute
  PraticheNuovaRoute: typeof PraticheNuovaRoute
  ClientiIndexRoute: typeof ClientiIndexRoute
  FattureIndexRoute: typeof FattureIndexRoute
  PraticheIndexRoute: typeof PraticheIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spese': {
      id: '/spese'
      path: '/spese'
      fullPath: '/spese'
      preLoaderRoute: typeof SpeseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scadenze': {
      id: '/scadenze'
      path: '/scadenze'
      fullPath: '/scadenze'
      preLoaderRoute: typeof ScadenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimposta-password': {
      id: '/reimposta-password'
      path: '/reimposta-password'
      fullPath: '/reimposta-password'
      preLoaderRoute: typeof ReimpostaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recupera-password': {
      id: '/recupera-password'
      path: '/recupera-password'
      fullPath: '/recupera-password'
      preLoaderRoute: typeof RecuperaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novita': {
      id: '/novita'
      path: '/novita'
      fullPath: '/novita'
      preLoaderRoute: typeof NovitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratiche/': {
      id: '/pratiche/'
      path: '/pratiche'
      fullPath: '/pratiche/'
      preLoaderRoute: typeof PraticheIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatture/': {
      id: '/fatture/'
      path: '/fatture'
      fullPath: '/fatture/'
      preLoaderRoute: typeof FattureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti/': {
      id: '/clienti/'
      path: '/clienti'
      fullPath: '/clienti/'
      preLoaderRoute: typeof ClientiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratiche/nuova': {
      id: '/pratiche/nuova'
      path: '/pratiche/nuova'
      fullPath: '/pratiche/nuova'
      preLoaderRoute: typeof PraticheNuovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratiche/$caseId': {
      id: '/pratiche/$caseId'
      path: '/pratiche/$caseId'
      fullPath: '/pratiche/$caseId'
      preLoaderRoute: typeof PraticheCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatture/nuova': {
      id: '/fatture/nuova'
      path: '/fatture/nuova'
      fullPath: '/fatture/nuova'
      preLoaderRoute: typeof FattureNuovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatture/$invoiceId': {
      id: '/fatture/$invoiceId'
      path: '/fatture/$invoiceId'
      fullPath: '/fatture/$invoiceId'
      preLoaderRoute: typeof FattureInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti/nuovo': {
      id: '/clienti/nuovo'
      path: '/clienti/nuovo'
      fullPath: '/clienti/nuovo'
      preLoaderRoute: typeof ClientiNuovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clienti/$clientId': {
      id: '/clienti/$clientId'
      path: '/clienti/$clientId'
      fullPath: '/clienti/$clientId'
      preLoaderRoute: typeof ClientiClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImpostazioniRoute: ImpostazioniRoute,
  LoginRoute: LoginRoute,
  NovitaRoute: NovitaRoute,
  PrivacyRoute: PrivacyRoute,
  RecuperaPasswordRoute: RecuperaPasswordRoute,
  RegisterRoute: RegisterRoute,
  ReimpostaPasswordRoute: ReimpostaPasswordRoute,
  ScadenzeRoute: ScadenzeRoute,
  SpeseRoute: SpeseRoute,
  TerminiRoute: TerminiRoute,
  ClientiClientIdRoute: ClientiClientIdRoute,
  ClientiNuovoRoute: ClientiNuovoRoute,
  FattureInvoiceIdRoute: FattureInvoiceIdRoute,
  FattureNuovaRoute: FattureNuovaRoute,
  PraticheCaseIdRoute: PraticheCaseIdRoute,
  PraticheNuovaRoute: PraticheNuovaRoute,
  ClientiIndexRoute: ClientiIndexRoute,
  FattureIndexRoute: FattureIndexRoute,
  PraticheIndexRoute: PraticheIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
